version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/mariadb/"
    update_schedule: "daily"
  - package_manager: "java:maven"
    directory: "/mysql/"
    update_schedule: "daily" 